### ISSUE TITLE
high disk usage from unconditional event logging

### ISSUE THREAD

**Issue by BenLubar** [libp2p/go-addr-util#36]
Can this be removed?

https://github.com/libp2p/go-addr-util/blob/11a461be805deb5a33c794b64ec7012224e240c9/addr.go#L101

**Comment by Stebalien** [comment]
Yeah, I have no idea why that's there.

**Comment by aronchick** [comment]
I'd like to take this on as a first issue - do you just want me to remove it and do a PR on it?

**Comment by marten-seemann** [comment]
Fixed by #38.
